@host = https://localhost
@port = 7000
@Restaurant.API_HostAddress = {{host}}:{{port}}
@KFC.Guid = 8dd54ded-435b-4d74-6af7-08dc895affe2
@testUser.Token = CfDJ8KppXvv35Z1MvC9Y7rPN44bs4Stf4gywZu-7jWkpQF1CQU68TsnQjM32jWJbBFAicq0d6aqvXzqpyTePwFwQhN9WYQG4oScMvA-WavE9Cxxg8Qt034nBxYg6UpQpONGpTtD3ug8AFlm89Vu1ulaEy738hSYr6v6M-KpSq2HMZJDHRH8EEdgGcxbfmUbbcxo6tU81ALLPcpT1Dykq1ggbHj88sZUw1wEJipNsBwhUqBiU3PUvTjKPCybvZ_mgW1tgFQAjGGBVn71EbF6tII4FmzAxpikENkJ0inoqQH50FQX1dLMaohvWFe4JaCGTWI-K7RjlF75ctbANd0QfUTxVtDws-f7YXNA-9K6ThKgG6QgcekGkb1ae5enZBcNWcKNd3lOp8RQtUJfMCXBK_LugbrnpfFGuktbB0_jDJeI78g4DWwwUSmvtGGfvON4wvoJJU4bDtOOKwuUL64IB3jaPFQkQPlnNObfmE_hhGemPT_hpj6-juiBJEK7_QthnseL4KiYitkS4mVjeiJ2bEp5Q9A2dGuiGCF2v3qRoOhjfC48a7H6U0q64Ld0Vo3wv3LKkbMG75eq02TZ2LIk6vShT-W2AcbHg58lOUk-Wdb4jX83wIr8-y9L2biqFEjmmZprwSKrGrzTow-ArW3IKjqCDkwJDkHO9RZTdU1L1z_t0TKbeFQFJItsln5lM8cg5vbgX6g


### Get All Restaurants
GET {{Restaurant.API_HostAddress}}/api/restaurants
Authorization: Bearer {{testUser.Token}}

### Get Restaurant By Id
GET {{Restaurant.API_HostAddress}}/api/restaurants/{{KFC.Guid}}

### Get Restaurant By Id - Negative Test
GET {{Restaurant.API_HostAddress}}/api/restaurants/1

### Create Restaurant
POST {{Restaurant.API_HostAddress}}/api/restaurants
Content-Type: application/json

{
"Name": "Spicy Delights",
"Description": "A culinary experience like no other",
"Category": "Fine Dining",
"HasDelivery": true,
"ContactEmail": "info@gourmetdelights.com",
"ContactNumber": "555-123-4567",
"City": "Metropolis",
"Street": "456 Gourmet Avenue",
"PostalCode": "54321"
}

### Delete Restaurant
DELETE {{Restaurant.API_HostAddress}}/api/restaurants/12aaa840-2cf0-4a8e-0a0e-08dc8bdddb47

### Update Restaurant
PATCH {{Restaurant.API_HostAddress}}/api/restaurants/f01a2f11-e5ce-4a0d-c94f-08dc8bdd2a36
Content-Type: application/json

{
"Name": "Spicy Delights updated",
"Description": "A culinary experience like no other updated",
"HasDelivery": false
}

### Create new dish
POST {{Restaurant.API_HostAddress}}/api/restaurants/{{KFC.Guid}}/dishes
Content-Type: application/json

{
  "Name": "Chicken Wings",
  "Description": "Finger-licking good", 
  "Price": 12.99,
  "KiloCalories": 500
}

### Delete dish by id for a restaurant
DELETE {{Restaurant.API_HostAddress}}/api/restaurants/{{KFC.Guid}}/dishes/65bc00f1-69b8-433c-ad56-08dc977bf71c

### Register User
POST {{Restaurant.API_HostAddress}}/api/identity/register
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "Password1!"
}

### Login User
POST {{Restaurant.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "Password1!"
}

### Register User for role Admin
POST {{Restaurant.API_HostAddress}}/api/identity/register
Content-Type: application/json

{
  "email": "admin@test.com",
  "password": "Password1!"
}

### Register User for role Owner
POST {{Restaurant.API_HostAddress}}/api/identity/register
Content-Type: application/json

{
  "email": "owner@test.com",
  "password": "Password1!"
}

### Register User for role User
POST {{Restaurant.API_HostAddress}}/api/identity/register
Content-Type: application/json

{
  "email": "user@test.com",
  "password": "Password1!"
}