@host = https://localhost
@port = 7000
@Restaurant.API_HostAddress = {{host}}:{{port}}
@KFC.Guid = 8dd54ded-435b-4d74-6af7-08dc895affe2

### Get All Restaurants
GET {{Restaurant.API_HostAddress}}/api/restaurants

### Get Restaurant By Id
GET {{Restaurant.API_HostAddress}}/api/restaurants/{{KFC.Guid}}

### Get Restaurant By Id - Negative Test
GET {{Restaurant.API_HostAddress}}/api/restaurants/1

### Create Restaurant
POST {{Restaurant.API_HostAddress}}/api/restaurants
Content-Type: application/json

{
"Name": "Spicy Delights",
"Description": "A culinary experience like no other",
"Category": "Fine Dining",
"HasDelivery": true,
"ContactEmail": "info@gourmetdelights.com",
"ContactNumber": "555-123-4567",
"City": "Metropolis",
"Street": "456 Gourmet Avenue",
"PostalCode": "54321"
}

### Delete Restaurant
DELETE {{Restaurant.API_HostAddress}}/api/restaurants/12aaa840-2cf0-4a8e-0a0e-08dc8bdddb47

### Update Restaurant
PATCH {{Restaurant.API_HostAddress}}/api/restaurants/f01a2f11-e5ce-4a0d-c94f-08dc8bdd2a36
Content-Type: application/json

{
"Name": "Spicy Delights updated",
"Description": "A culinary experience like no other updated",
"HasDelivery": false
}

### Create new dish
POST {{Restaurant.API_HostAddress}}/api/restaurants/{{KFC.Guid}}/dishes
Content-Type: application/json

{
  "Name": "Chicken Wings",
  "Description": "Finger-licking good", 
  "Price": 12.99,
  "KiloCalories": 500
}